### 게시글 작성

POST http://localhost:8080/api/posts
Content-Type: application/json

{
  "title": "제목입니다.",
  "content": "내용입니다."
}


### 게시글 삭제

DELETE http://localhost:8080/api/posts/1
Content-Type: application/json

### 게시글 단건 조회

GET http://localhost:8080/api/posts/1
Content-Type: application/json


### 게시글 리스트 조회

## /api/posts?page=1&size=5


GET http://localhost:8080/api/posts?page=1&size=3
Content-Type: application/json


### 댓글 작성

POST http://localhost:8080/api/posts/2/comments
Content-Type: application/json

{
  "author":  "악플러",
  "password":  "123444444",
  "content":  "555죽어죽어죽어444444"
}

### 댓글 조회

GET http://localhost:8080/api/posts/1/comments?page=1&size=5
Content-Type: application/json

    @GetMapping("/api/posts/{postId}/comments")



